### ISSUE TITLE
draw my data

### ISSUE THREAD

**Issue by mdsumner** [pbricher/SOOS#4]
http://robertgrantstats.co.uk/drawmydata.html

This is worth looking at for how we can capture a "track", and maybe keep editing the table of coordinates

**Comment by pbricher** [comment]
Does it get us around the problem of adding/editing a waypoint after drawing the initial line?

 

Cheers,

Pip

 

 

 

Dr Pip Bricher

Data Officer, Southern Ocean Observing System  <http://www.soos.aq/> www.soos.aq

Data Officer, Antarctic Gateway Partnership  <http://www.imas.utas.edu.au/antarctic-gateway-partnership> http://www.imas.utas.edu.au/antarctic-gateway-partnership

**Comment by mdsumner** [comment]
With some work, yes :)  I actually think we'll find a tool out there somewhere, surely someone's already done this

**Comment by mdsumner** [comment]
This is something we could probably use: https://github.com/henrythasler/Leaflet.Geodesic

**Comment by pbricher** [comment]
Surely!

 

Dr Pip Bricher

Data Officer, Southern Ocean Observing System  <http://www.soos.aq/> www.soos.aq

Data Officer, Antarctic Gateway Partnership  <http://www.imas.utas.edu.au/antarctic-gateway-partnership> http://www.imas.utas.edu.au/antarctic-gateway-partnership

**Comment by pbricher** [comment]
Golly! If that worked (and we found an equivalent tool for James’ version) it would allow us to switch between projections comfortably.  I suspect this might be heading into version 3 territory though…

 

Cheers,

Pip

 

Dr Pip Bricher

Data Officer, Southern Ocean Observing System  <http://www.soos.aq/> www.soos.aq

Data Officer, Antarctic Gateway Partnership  <http://www.imas.utas.edu.au/antarctic-gateway-partnership> http://www.imas.utas.edu.au/antarctic-gateway-partnership

**Comment by mdsumner** [comment]
This is close: http://geojson.io/

On that map we can draw a sequence of *points*, and then under Table - add a new column and enter dates. This is a "single-coordinate" as POINT model, so each x-y can have more attributes. You can even "edit" the map and move points around. New points are always "next", so the back-end would need to interpret a date and re-order the points, and draw a new line. 

Anyway, that's enough for a competent programmer to work with, I think. :)

**Comment by pbricher** [comment]
Now that looks promising…

 

Dr Pip Bricher

Data Officer, Southern Ocean Observing System  <http://www.soos.aq/> www.soos.aq

Data Officer, Antarctic Gateway Partnership  <http://www.imas.utas.edu.au/antarctic-gateway-partnership> http://www.imas.utas.edu.au/antarctic-gateway-partnership
